import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  categories = [
    {
      id: 1,
      type: 'Fruits',
      imageCat: 'assets/imagesCategory/catFruits.jpg',
    },
    {
      id: 2,
      type: 'Légumes',
      imageCat: 'assets/imagesCategory/catLegumes.jpg',
    },
    {
      id: 3,
      type: 'Epices',
      imageCat: 'assets/imagesCategory/epices3.jpeg',
    }
  ];

  produits = [
    {id :1, titre : 'Ananas', image : 'assets/fruits/ananas.jpg', prix : (3).toFixed(2), cat : 'Fruits', 
    def: 'C\'est un fruit tropical par excellence, est offert toute l\’année dans nos supermarchés. Originaire d\'Amérique du Sud, il se cuisine aussi bien dans les desserts que dans des plats sucrés-salés. Riche en vitamines et minéraux, il apporte une multitude de bienfaits pour la santé.',
     link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=ananas_nu', 'https://cuisine.journaldesfemmes.fr/encyclopedie-produits/1956788-ananas/'], source : 'passeportsante.net'},
    {id :2, titre : 'Cerises', image : 'assets/fruits/cerises.jpg', prix : (6).toFixed(2), cat : 'Fruits', 
    def:'La cerise douce (la variété Bing est la plus connue) se consomme fraîche, surtout dans les desserts, les salades ou les sauces. La cerise acidulée (surtout offerte en conserve, congelée ou séchée) sert plutôt à la préparation de tartes, de confitures et de jus. Cinq fois plus riche en antioxydants que la cerise douce, elle contribuerait à prévenir le cancer et plusieurs autres maladies.',
     link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=cerise_nu', 'https://www.creapharma.ch/cerise-nutrition.htm', 'https://www.santemagazine.fr/alimentation/aliments-et-sante/fruits/8-bienfaits-de-la-cerise-337039'], source: 'passeportsante.net'}, 
    {id :3, titre : 'Citron', image : 'assets/fruits/citron.jpg', prix : (2.50).toFixed(2), cat : 'Fruits',
  def: 'Le citron (ou citron jaune) est un agrume, fruit du citronnier (Citrus limon). Il existe sous deux formes : le citron doux, fruit décoratif de cultivars à jus peu ou pas acide néanmoins classé Citrus limon (L.) Burm. f. (classification de Tanaka) ; et le citron acide, le plus commun de nos jours, dont le jus a un pH d\'environ 2,5.',
   link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=citron_lime_nu','https://mr-ginseng.com/citron/', 'https://www.lanutrition.fr/bien-dans-son-assiette/aliments/fruits/citron'], source: 'passeportsante.net'},
    {id :4, titre : 'Clémentines', image : 'assets/fruits/clementine.jpeg',prix : (3.10).toFixed(2), cat : 'Fruits', def: 'La clémentine est un agrume issu d\'un croisement entre une mandarine et une orange. On l\'apprécie en hiver pour faire le plein de vitamines et apporter une touche sucrée à la fin de nos repas ou en collation. Riche en antioxydants, la clémentine va permettre de lutter contre certaines pathologies.',
  link : ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=clementine_mandarine_tangerine_nu', 'https://www.marmiton.org/ingredients/fruits_clementine.aspx', 'https://www.canalvie.com/recettes/savoir-cuisiner/guide-des-aliments/clementine-1.1125486'], source: 'passeportsante.net'},
    {id :5, titre : 'Dattes Ajwa', image : 'assets/fruits/dattes_ajwa.jpeg', prix : (7.50).toFixed(2), cat : 'Fruits', def:'Les dattes Ajwa sont une variété de datte douce et fruitée, avec une texture fine, en provenance d\'Arabie Saoudite. Ils sont cultivés à Al Madina. En fait, les dattes d\'Ajwa sont les dattes les plus célèbres de cette région et pour de très bonnes raisons, comme vous le verrez ci-dessous.',
  link:['https://www.miel-imperial.com/sante-et-bien-etre/56-dattes-ajwa.html'], source:'alwosta.tn'},
    {id :6, titre : 'Dattes', image : 'assets/fruits/dattes.jpeg', prix : (5).toFixed(2), cat : 'Fruits', def:'Fraîches ou séchées, les dattes constituent une bonne source de fibres alimentaires. Leur contenu élevé en glucides en fait des fruits à haute teneur énergétique, parfaits pour les activités sportives intenses. De plus, elles contiennent une forte concentration d’antioxydants',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=datte_nu', 'https://www.alwosta.tn/fr/blog/59_bienfaits-et-vertus-medicinales-de-la-datte-ajwa.html', 'https://sante.journaldesfemmes.fr/fiches-sante-du-quotidien/2499926-les-bienfaits-des-dattes-pour-la-sante/'], source: 'passeportsante.net'},
    {id :7, titre : 'Fraises', image : 'assets/fruits/fraises.jpeg', prix : (4.50).toFixed(2), cat : 'Fruits', def:'A l\'arrivée du printemps, la fraise fait son apparition sur nos étals pour le bonheur des plus gourmands. Ce petit fruit rouge est riche en vitamines et minéraux et possède de nombreux bienfaits pour la santé. On la consomme généralement en dessert, crue avec du sucre ou de la chantilly, mais elle se marie également très bien avec des salades pour un mélange sucré/salé. ', 
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=fraise_nu', 'https://chefsimon.com/articles/produits-les-fraises'], source: 'passeportsante.net'},
    {id :8, titre : 'Framboises', image : 'assets/fruits/framboises.jpg', prix : (3.70).toFixed(2), cat : 'Fruits', def: 'Framboises et mûres se déclinent en plusieurs couleurs, grosseurs, textures et saveurs. Leur forte teneur en antioxydants contribue à prévenir les maladies cardiovasculaires, les cancers et diverses maladies chroniques',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=framboise_mure_nu', 'https://informationsnutritionnelles.fr/framboise', 'https://cuisine.journaldesfemmes.fr/recette-framboise'], source: 'passeportsante.net'},
    {id :9, titre : 'Fruits de la passion', image : 'assets/fruits/fruit_passion.jpg', prix : (3).toFixed(2), cat : 'Fruits', def: 'Le fruit de la passion, aussi appelé grenadille, est une petite baie tropicale grosse comme un oeuf. Sa chair parfumée contient de nombreuses petites graines noires qui constituent une très bonne source de fibres alimentaires.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=fruit_passion_nu', 'https://www.jardiner-malin.fr/sante/fruit-de-la-passion-bienfaits-vertu.html'], source: 'passeportsante.net'},
    {id :10, titre : 'Kiwi', image : 'assets/fruits/kiwi.jpg', prix : (2.70).toFixed(2), cat : 'Fruits', def: 'Un seul kiwi renferme une quantité impressionnante de fibres. Grâce aux antioxydants qu\’il contient, le consommer régulièrement préviendrait l\’apparition de maladies cardiovasculaires et de certains cancers.', 
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=kiwi_nu', 'https://docteurbonnebouffe.com/bienfaits-kiwis-sante/'], source: 'passeportsante.net'},
    {id :11, titre : 'Mangues', image : 'assets/fruits/mangue1.jpeg', prix : (2).toFixed(2), cat : 'Fruits', def: 'La mangue est le fruit tropical le plus consommé au monde après la banane. Sa chair orangée et juteuse est une bonne source de fibres et de vitamine C. Elle aurait un potentiel anticancer, notamment grâce à son contenu en antioxydants.', 
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=mangue_nu', 'https://cuisine.journaldesfemmes.fr/encyclopedie-produits/1957578-mangue/', 'https://www.canalvie.com/recettes/savoir-cuisiner/guide-des-aliments/mangue-1.1130971'], source: 'passeportsante.net'},
    {id :12, titre : 'Melon', image : 'assets/fruits/melon.jpg', prix : (1.50).toFixed(2), cat : 'Fruits', def: 'Le Melon (Cucumis melo) est une plante herbacée annuelle originaire d\'Afrique intertropicale, appartenant à la famille des Cucurbitacées et largement cultivée comme plante potagère pour son faux-fruit comestible. Le terme désigne aussi le fruit climactérique lui-même très savoureux, sucré et parfumé.', 
  link: ['https://www.passeportsante.net/fr/Actualites/Dossiers/DossierComplexe.aspx?doc=melon-bienfaits-sante-potassium', 'https://www.marmiton.org/ingredients/fruits_melon.aspx'], source: 'Wikipédia'},
    {id :13, titre : 'Mûres', image : 'assets/fruits/mures.jpeg', prix : (3.10).toFixed(2), cat : 'Fruits', def: 'La mûre est de couleur noir bleuâtre à maturité, en général à la fin de l\'été, vers septembre. Comestible, d\'un goût sucré, la mûre est en réalité un faux-fruit car elle n\'est pas issue du pistil de la fleur mais formée de l\'agrégation des carpelles modifiées et transformées en petites drupes (drupéoles) qui restent adhérentes au réceptacle floral. Les fleurs de la mûre sauvage sont blanches ou blanc rosé, de deux à trois centimètres de diamètre, regroupées en corymbes ; elles ont cinq sépales, cinq pétales et de nombreuses étamines.', 
  link: ['https://www.lanutrition.fr/bien-dans-son-assiette/aliments/fruits/mure/les-varietes-de-mures', 'https://www.jardiner-malin.fr/sante/mure-bienfaits-vertu.html'], source: 'Wikipédia'},
    {id :14, titre : 'Myrtilles', image : 'assets/fruits/myrtilles.jpeg', prix : (3.30).toFixed(2), cat : 'Fruits', def: 'La myrtille (Vaccinium myrtillus) appartient à la famille des Ericaceae (Ogawa, 2014).Cette plante est originaire d\’Europe du Nord, et s\’étend désormais en Amérique du Nord et en Asie (Chu, 2013).', 
  link: ['http://www.aprifel.com/fiche-nutri-produit-myrtille,12.html', 'https://www.passeportsante.net/fr/Solutions/PlantesSupplements/Fiche.aspx?doc=bleuet_ps'], source : 'aprifel.com'},
    {id :15, titre : 'Noix de coco', image : 'assets/fruits/noix_coco.jpeg', prix : (3.60).toFixed(2), cat : 'Fruits', def: 'La noix de coco, brune et chevelue à l\’extérieur, blanche et crémeuse à l\’intérieur, est un fruit très répandu dans les régions tropicales et subtropicales. La plupart des parties de l’arbre et du fruit peuvent se prêter à une foule d’applications culinaires et non culinaires, ce qui a valu au cocotier le titre d\’ arbre aux mille usages  en Malaisie. Comme la noix de coco a besoin d’un climat chaud en permanence pour se développer, sa culture est impensable au Canada; c\’est pourquoi il s\’agit d’un des principaux aliments importés au pays.', 
  link: ['https://www.avogel.ca/fr/nutrition/ingredients/noix-de-coco/', 'https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=noix_coco_nu', 'https://www.selection.ca/cuisine/nutrition/la-noix-de-coco-et-ses-bienfaits'], source: 'avogel.ca'},
    {id :16, titre : 'Oranges', image : 'assets/fruits/orange1.jpeg', prix : (2.65).toFixed(2), cat : 'Fruits', def: 'L\'orange est un fruit juteux, sucré, excitant et il contient de la vitamine C. On utilise ce fruit pour les salades de fruits, les confitures, ou pour consommer son jus. Les oranges sanguines tirent leur nom de la couleur totalement ou partiellement rouge de leur chair.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=orange_nu', 'https://www.lanutrition.fr/bien-dans-son-assiette/aliments/fruits/orange/les-atouts-sante-de-lorange', 'https://www.lesfruitsetlegumesfrais.com/fruits-legumes/agrumes/orange/carte-identite'],source: 'Wikipédia'},
    {id :17, titre : 'Pastèques', image : 'assets/fruits/pasteque1.jpeg', prix : (3).toFixed(2), cat : 'Fruits', def: 'Originaire d\'Afrique et plus précisément de la vallée du Nil, la pastèque est le fruit d\'une plante annuelle à tige grimpante. Elle peut peser entre 3 et 5 kilos, ce qui fait d\'elle l\'un des fruits les plus gros de la famille des cucurbitacées.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=pasteque_nu', 'https://www.lanutrition.fr/tout-savoir-sur-la-pasteque'], source: 'journaldesfemmes.fr'},
    {id :18, titre : 'Poires', image : 'assets/fruits/poires.jpg',prix : (2.30).toFixed(2), cat : 'Fruits', def: 'La poire est le fruit à pépins comestible au goût doux et sucré, produit par le poirier commun (Pyrus communis L.), arbre de la famille des Rosaceae.', 
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=poire_nu', 'https://sante.lefigaro.fr/mieux-etre/nutrition-aliments/poire/quels-bienfaits', 'https://sante.journaldesfemmes.fr/fiches-sante-du-quotidien/2595168-poire-bienfaits-sante-calories-contre-indication/'], source: 'Wikipédia'},
    {id :19, titre : 'Pommes', image : 'assets/fruits/pommes1.jpeg', prix : (2.50).toFixed(2), cat : 'Fruits', def: 'La pomme est un fruit comestible à pépins d\'un goût sucré et acidulé et à la propriété plus ou moins astringente selon les variétés. D\'un point de vue botanique, il s\'agit d\'un faux-fruit. Elle est produite par les pommiers, des arbres du genre Malus.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=pomme_nu', 'https://www.canalvie.com/recettes/savoir-cuisiner/guide-des-aliments/pomme-1.1125220'], source: 'Wikipédia'},
    {id :20, titre : 'Litchi', image : 'assets/fruits/litchi.jpg', prix : (3.80).toFixed(2), cat : 'Fruits', def: 'Le litchi est un fruit provenant d\’un arbre nommé Litchi chinensis, une espèce d\'arbre tropical originaire du Sud de la Chine. Cet arbre peut atteindre jusqu\’à 20 mètres et produit des quantités élevées de litchi, soit de 100 à 150 kg par année. Il est également cultivé en Inde, en Thaïlande, en Afrique du Sud, En Israël, au Mexique, en Australie et aux États-Unis. C’est un proche parent du longane et du ramboutan. \n Il mesure entre 2 et 5 cm et est entouré d’une mince coque rugueuse, qui devient rigide après la cueillette. Elle a toutefois l\’avantage d’être facile à décortiquer. Le fruit arrête de murir après la cueillette. À pleine maturité, la coque est rouge ou rosé. Si la coque est ternie ou brunie, c\’est que le fruit est trop vieux. La chair est blanche, translucide, juteuse, parfumée et très sucrée. Le litchi comprend également un noyau central brun et lisse qui n’est pas comestible.\nOn compare souvent le goût du litchi à un mélange de fraise, de rose et de muscat.\nIl tolère très mal le froid, le transport et les délais de mise en marché.', 
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=litchi', 'https://cuisine.journaldesfemmes.fr/encyclopedie-produits/1955590-litchi/', 'https://www.canalvie.com/recettes/savoir-cuisiner/guide-des-aliments/litchi-1.1183065'], source: 'passeportsante.net'},
    {id :21, titre : 'Cannelle', image : 'assets/epices/cannelle1.jpeg', prix : (2).toFixed(2), cat : 'Epices', def: 'La cannelle est une épice provenant de l\' écorce intérieure d\'une des espèces de cannelier du genre Cinnamomum. Les quatre principales sortes de cannelle sont la cannelle de Padang (en), la cannelle de Chine ou casse, la cannelle de Saïgon (en) et la cannelle de Ceylan ou  vraie cannelle.', 
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=cannelle_nu', 'https://mr-ginseng.com/cannelle/'], source: 'Wikipédia'},
    {id :22, titre : 'Cumin', image : 'assets/epices/cumin.jpeg', prix : (1.50).toFixed(2), cat : 'Epices', def: 'Le cumin (Cuminum cyminum) est une plante herbacée annuelle de la famille des Apiacées (Ombellifères).\nLe cumin (ou Cuminum en latin) est originaire du Proche-Orient. Il y est apparu comme épice, à fumer ou pour apprêter des mets, puisque son goût est terreux lorsque non apprêté. Il est de la même famille que le persil. Les synonymes de cette épice sont nombreux et incluent le cumin blanc , cumin du Maroc ou faux anis.',
  link: ['https://www.lanutrition.fr/cumin-graines-', 'https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=cumin_nu'], source: 'Wikipédia'},
    {id :23, titre : 'Curcuma', image : 'assets/epices/curcuma.jpg', prix : (2.50).toFixed(2), cat : 'Epices', def: 'Le curcuma (Curcuma longa) est une plante herbacée rhizomateuse vivace du genre Curcuma de la famille des Zingibéracées originaire du sud ou sud-est asiatique. De ses rhizomes réduits en poudre est extraite l\'épice homonyme.\nLe curcuma, ingrédient principal des carry ou curry, est particulièrement présent dans la vie socioculturelle du sous-continent indien, où il est considéré comme une plante exceptionnelle en regard de ses nombreuses propriétés (épice, conservateur de nourriture, agent colorant, cosmétique et médicinal). Répandu dans le sud-est de l\'Asie depuis l\'antiquité, le curcuma fait l\'objet de nombreuses études scientifiques dans le monde entier, afin de mieux cerner ses propriétés alimentaires et médicales.\nLe curcuma est également un enjeu économique pour l\'Inde, son premier producteur mondial, ainsi que pour de nombreux autres pays producteurs.',
  link: ['https://www.passeportsante.net/fr/Solutions/PlantesSupplements/Fiche.aspx?doc=curcuma_ps', 'https://sante.journaldesfemmes.fr/fiches-sante-du-quotidien/2540888-curcuma-epice-plante-bienfait-danger/'], source: 'Wikipédia'},
    {id :24, titre : 'Clous de girofles', image : 'assets/epices/girofles1.jpeg', prix : (1.70).toFixed(2), cat : 'Epices', def: 'Le giroflier ou girofle (Syzygium aromaticum) est une espèce de plantes de la famille des Myrtaceae et du genre Syzygium. Les girofliers sont des arbres originaires d\'Indonésie dont les boutons floraux sont appelés Clous de Girofle.',
  link: ['https://www.grands-meres.net/clou-de-girofle/', 'https://www.mr-plantes.com/2017/05/clou-de-girofle/', 'https://sante.journaldesfemmes.fr/fiches-sante-du-quotidien/2604881-clou-de-girofle-vertu-infusion-dent-danger-grossesse-infusion/'], source: 'Wikipédia'},
    {id :25, titre : 'Paprika', image : 'assets/epices/paprika.jpeg', prix : (1.60).toFixed(2), cat : 'Epices', def: 'Le paprika, aussi connu sous le terme piment doux, est une épice en poudre de couleur rouge obtenue à partir du fruit mûr, séché et moulu du piment doux ou poivron (Capsicum annuum, de la famille des Solanaceae). Le terme désigne aussi le fruit en lui-même.\nL\'épice est utilisée en cuisine pour sa saveur âcre et légèrement piquante et sa couleur rouge.\nLes principaux types d\'épices sont le paprika de Hongrie, fait à partir des fruits seulement, et le paprika royal, fabriqué avec les graines, les tiges et les fruits.\nEn plus d\'être largement utilisé dans la plupart des pays tropicaux et notamment en Asie, il est très présent dans la cuisine maghrébine, espagnole, serbe, turque et hongroise.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=paprika_nu', 'https://www.actions-ecologiques.fr/bienfaits-paprika/'], source: 'Wikipédia'},
    {id :26, titre : 'Poivre', image : 'assets/epices/poivre.jpeg', prix : (1.50).toFixed(2), cat : 'Epices', def: 'Le poivre est une épice obtenue à partir des baies de différentes espèces de poivriers, des plantes de la famille des pipéracées. En France, seuls ont droit légalement à l\'appellation de poivre sans plus de précision les fruits du poivrier noir (Piper nigrum) qui donnent le poivre vert, blanc, rouge ou noir. Les fruits du Piper longum donnent le poivre long, ceux du Piper cubeba le poivre cubèbe, ceux du Piper borbonense le poivre de Voatsiperifery.\nPar analogie, d\'autres épices qui proviennent de plantes bien différentes reprennent ce nom vernaculaire, mais ces faux poivres ont d\'autres caractéristiques botaniques et donnent des saveurs différentes.',
  link: ['https://ileauxepices.com/blog/2013/01/08/histoire-du-poivre/wpid871/', 'https://www.mr-plantes.com/2018/04/poivre-noir/'], source: 'Wikipédia'},
    {id :27, titre : 'Raz El Hannout', image : 'assets/epices/raz_el_hannout.jpg', prix : (2).toFixed(2), cat : 'Epices', def: 'Le ras el-hanout (arabe : رأس الحانوت), parfois orthographié raz-el-hanout, littéralement \« tête de l\'épicerie \», est un mélange d\'épices d\'origine marocaine utilisé dans la cuisine des pays du Maghreb. On le trouve en vente chez les marchands d\'épices, dans tous les souks, soit moulu, soit à l\'état brut. Son prix varie du simple au double selon les ingrédients employés. Il est aussi surnommé \« curry du Maghreb \».\nLe ras el-hanout est employé dans la préparation du tajine, de la mloukhia (mrouzia) mais s\'utilise aussi pour le couscous.\nComposé et dosé suivant la science et la fantaisie du vendeur, le ras el-hanout est l\'épice de l\'Aïd el-Kebir, s\'utilise aussi dans certains plats d\'hiver censés réchauffer le corps et est souvent ajouté dans la cuisson du gibier.',
  link: ['https://www.panierdesaison.com/2016/09/ras-el-hanout.html', 'https://www.cuisineaz.com/articles/raz-el-hanout-2441.aspx', 'https://anaca3.com/blog/le-ras-el-hanout-fait-il-grossir/'], source: 'Wikipédia'},
    {id :28, titre : 'Safran', image : 'assets/epices/safran1.jpeg', prix : (4).toFixed(2), cat : 'Epices', def: 'Le safran est un produit agricole classé dans la famille des épices. Il est obtenu par la culture de Crocus sativus L. (Iridacée) et par prélèvement et déshydratation des trois stigmates rouges (extrémités distales des carpelles de la plante), dont la longueur varie généralement entre 2,5 à 3,2 cm1.\nLe style et les stigmates sont souvent utilisés en cuisine, comme assaisonnement ou comme agent colorant. Le safran, appelé parfois \« or rouge \», est l\'épice la plus laborieuse à produire au monde et donc de haute valeur. Il est originaire de Crète, puis s\'est répandu au Moyen-Orient. Il a été cultivé pour la première fois dans les provinces grecques, par la civilisation minoenne, il y a plus de 35 siècles.\nLe safran est caractérisé par un goût amer et un parfum proche de l\'iodoforme, ou du foin, causé par la picrocrocine et le safranal. Il contient également un caroténoïde, la crocine, qui donne une couleur jaune-or aux plats contenant du safran. Ces caractéristiques font du safran un condiment fortement prisé pour de nombreuses spécialités culinaires dans le monde entier, notamment dans la cuisine persane. Le safran possède également des applications médicales.\nLe mot \« safran \» est un emprunt au latin médiéval safranum, aussi ancêtre du portugais açafrão, de l\'italien zafferano et de l\'espagnol azafrán. Safranum est un emprunt à l\’arabe zaʿfarān (زَعْفَرَان), \« safran, crocus à safran \», peut-être croisé avec aṣfar (أَصْفَر), \« jaune \».\nS\'appuyant sur la présence de cultures de safran sur le plateau iranien, on suppose que le mot arabe zaʿfarān proviendrait d’un persan zar-parân (زرپران), proprement \« à plumes dorées \», composé de zar (زر), \« or \» et par (پر), \« plume \»',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=safran_nu', 'https://mr-ginseng.com/safran/'], source: 'Wikipédia'},
    {id :29, titre : 'Artichauts', image : 'assets/legumes/artichauts1.jpeg', prix : (4.50).toFixed(2), cat : 'Légumes', def: 'L’artichaut (Cynara cardunculus var. scolymus (L.) Benth.) est une plante dicotylédone de la famille des Astéracées (ou Composées) appartenant au genre Cynara.\nL\'artichaut lui-même est un chardon domestiqué et cultivé, de l\'espèce Cynara cardunculus, dont la variété sauvage est sans doute Cynara cardunculus var. sylvestris (Lamk.) Fiori, ayant donné naissance à deux formes \: C. cardunculus f. cardunculus, le cardon, et C. cardunculus f. scolymus, l\'artichaut. Ces deux formes ont longtemps été considérées comme des espèces différentes.',
  link: ['https://sante.journaldesfemmes.fr/fiches-sante-du-quotidien/2540870-artichaut-bienfaits-precautions/', 'https://www.passeportsante.net/fr/Solutions/PlantesSupplements/Fiche.aspx?doc=artichaut_ps'], source: 'Wikipédia'},
    {id :30, titre : 'Batavia', image : 'assets/legumes/batavia1.jpeg', prix : (1.50).toFixed(2), cat : 'Légumes', def: 'La batavia est une sorte de laitue craquante et à la saveur légèrement sucrée. Comme toutes les salades vertes, elle renferme beaucoup d\'eau mais peu de calories. Elle contient aussi beaucoup de fibres, indispensables au transit.\nSes apports en vitamines A et K sont également intéressants. A manger crue ou cuite, la batavia est donc un aliment à consommer sans restriction même en cas de régime minceur, bien au contraire.',
  link: ['https://jardinage.ooreka.fr/astuce/voir/568133/laitue-batavia', 'https://www.kazidomi.com/fr/blog/top-10-des-bienfaits-de-la-salades-n220'], source: 'Wikipédia'},
    {id :31, titre : 'Carottes', image : 'assets/legumes/carottes.jpeg', prix : (2.50).toFixed(2), cat : 'Légumes', def: 'La carotte, Daucus carota subsp. sativus, est une plante bisannuelle de la famille des apiacées (aussi appelées ombellifères), largement cultivée pour sa racine pivotante charnue, comestible, de couleur généralement orangée, consommée comme légume. La carotte représente après la pomme de terre le principal légume-racine cultivé dans le monde. C\'est une racine riche en carotène. La carotte est un tubercule d\'hypocotyle, c\'est-à-dire formé pour partie par l\'hypocotyle et pour l\'autre partie par la région supérieure de la racine, qui se sont tubérisés.',
  link: ['https://www.doctissimo.fr/nutrition/famille-d-aliments/guide-aliments/carotte', 'https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=carotte_nu'], source: 'Wikipédia'},
    {id :32, titre : 'Courgettes', image : 'assets/legumes/courgettes.jpeg', prix : (1.70).toFixed(2), cat : 'Légumes', def: 'La courgette est une plante herbacée de la famille des Cucurbitaceae, c\'est aussi le fruit comestible de cette plante. La courgette est un fruit courant en été, la fleur de courgette est aussi utilisée en cuisine. Les différentes variétés de courgettes sont des cultivars de l\'espèce Cucurbita pepo, et de la sous-espèce Cucurbita pepo subsp. pepo dont fait partie aussi la citrouille véritable.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=courgette_patisson_nu', 'https://sante.journaldesfemmes.fr/fiches-sante-du-quotidien/2593576-courgette-bienfaits-calories-precaution-allergie/'], source: 'Wikipédia'},
    {id :33, titre : 'Endives', image : 'assets/legumes/endives.jpg', prix : (1.60).toFixed(2), cat : 'Légumes', def: 'L\’endive (Cichorium intybus L. var. foliosum Hegi), nom commun de la chicorée de Bruxelles ou chicorée Witloof, appelée aussi chicon dans le Nord de la France, au Luxembourg et en Belgique, est une variété de chicorée amère (Cichorium intybus), plante bisannuelle de la famille des Astéracées, mais différente de celle qui donne la chicorée à café (Cichorium intybus var. sativum).Cette chicorée vivace à \« nombreuses feuilles \», comme son épithète sub-spécifique le précise, est surtout cultivée comme une plante annuelle pour ses \« chicons \», pousses blanchies obtenues par forçage et consommées comme légumes crus ou cuits. Contrairement à ce que son nom usuel pourrait laisser croire, cette salade n\'est pas une variété issue de l\'\« endive vraie \» des botanistes, une espèce voisine nommée Cichorium endivia L. qui donne les chicorées scaroles et frisées.',
  link: ['https://cuisine.journaldesfemmes.fr/encyclopedie-produits/1955277-endive/', 'https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=chicoree_endive_nu'], source: 'Wikipédia'},
    {id :34, titre : 'Epinards', image : 'assets/legumes/epinard.jpg', prix : (5).toFixed(2), cat : 'Légumes', def: 'L\'épinard (Spinacia oleracea) est une plante potagère, annuelle ou bisannuelle, de la famille des Chenopodiaceae ou des Amaranthaceae selon les classifications. Originaire de l\'Iran (il tire son nom du persan اسفناج āsfanāǧ), il est aujourd\'hui cultivé dans toutes les régions tempérées pour ses qualités nutritionnelles.\nIl est célébré dans la bande dessinée Popeye comme un légume riche en fer, qui donne sa force au héros, bien qu\'en réalité sa teneur en fer ne soit pas particulièrement élevée.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=epinard_nu', 'https://cuisine.journaldesfemmes.fr/encyclopedie-produits/1955107-epinard/'], source: 'Wikipédia'},
    {id :35, titre : 'Fenouil', image : 'assets/legumes/fenuil1.jpeg', prix : (2).toFixed(2), cat : 'Légumes', def: 'Fenouil est un nom vernaculaire ambigu désignant, en français, une multitude de plantes de genres divers, notamment de la famille des Apiaceae. Ce sont des plantes herbacées au feuillage aromatique, dont certaines sont consommables. Le mot fenouil provient du latin Foeniculum qui signifie foin (foenum) de petite taille (-culum est un diminutif), nom donné en raison de la finesse de son feuillage.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=fenouil_nu', 'https://www.lesfruitsetlegumesfrais.com/fruits-legumes/legumes-feuilles/fenouil/nutritions-et-bienfaits', 'https://bioasis.fr/fenouil/'], source: 'Wikipédia'},
    {id :36, titre : 'Haricots verts', image : 'assets/legumes/haricots.jpg', prix : (2.30).toFixed(2), cat : 'Légumes', def: 'Les haricots verts sont des gousses immatures du haricot commun (Phaseolus vulgaris) consommées comme légumes. Selon les variétés, leur couleur peut varier entre le jaune (haricots \« beurre \»), le vert et le violet. Des variétés ont été sélectionnées spécialement dans l\'objectif de ce type de récolte avant maturité, en recherchant certaines caractéristiques comme la tendreté, l\'absence de fils...\nLes haricots \« mangetout \» sont des variétés de haricots à gousse sans parchemin d\'où leur nom. Ils peuvent se consommer à un stade de maturité avancée avec des graines bien formées, mais encore jeunes, sans que la cosse soit devenue ligneuse.\nLes haricots verts sont commercialisés soit frais, soit surgelés, soit en conserve.', 
  link: ['https://informationsnutritionnelles.fr/haricot-vert', 'https://sante.lefigaro.fr/mieux-etre/nutrition-aliments/haricot-vert/quels-bienfaits'], source: 'Wikipédia'},
    {id :37, titre : 'Laitue', image : 'assets/legumes/laitue.jpeg', prix : (1.50).toFixed(2), cat : 'Légumes', def: 'La Laitue (Lactuca), au sens botanique du terme, est un genre de plante annuelle de la famille des Astéracées (Composées) dont certaines espèces sont cultivées pour leurs feuilles tendres consommées comme salade verte. Ce genre comprend plus de 100 espèces. La laitue la plus cultivée est l\'espèce Lactuca sativa à partir de laquelle les jardiniers ont sélectionné de nombreuses variétés et cultivars. Le genre Lactuca doit son nom au fait que ses espèces contiennent un latex blanc, le lactucarium (Lactuca dérive du latin lac, lactis, le lait) qui s\'écoule des blessures des tiges. La laitue est réputée pour ses vertus soporifiques, notamment sur les lapins, ce qui en fait un légume apprécié des jardiniers pour le potager.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=laitue_nu'], source: 'Wikipédia'},
    {id :38, titre : 'Navets', image : 'assets/legumes/navets1.jpeg', prix : (1.30).toFixed(2), cat : 'Légumes', def: 'Navets (Brassicarapa) sont un légume-racine et un membre de la famille des crucifères, avec d’autres légumes comme le bok choy, les choux de Bruxelles et le chou frisé.C’est l’une des cultures légumières les plus importantes au monde, car elles sont utilisées pour nourrir les humains et le bétail ().Les types les plus courants de navet sont violets, rouges ou verdâtres à l’extérieur et ont un bulbe à chair blanche – également appelé racine ou organe de stockage – qui pousse au-dessus du sol et a une peau lisse sans cicatrices ni racines latérales (). Leurs racines et leurs feuilles, également connues sous le nom de feuilles de navet, peuvent être consommées sans danger et, comme la plupart des légumes crucifères, elles sont appréciées pour leurs effets bénéfiques pour la santé.',
    link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=navet_nu'], source: 'infosante24.com'},
    {id :39, titre : 'Oignons rouges', image : 'assets/legumes/oignons_rouges1.jpeg', prix : (1.70).toFixed(2), cat : 'Légumes', def: 'voir \"oignons\"',
  link: ['https://www.deco.fr/jardin-jardinage/74024-comment-planter-et-cultiver-des-oignons-rouges'], source: 'Wikipédia'},
    {id :40, titre : 'Oignons', image : 'assets/legumes/oignons1.jpeg', prix : (1.50).toFixed(2), cat : 'Légumes', def: 'L\'oignon est une espèce de plantes herbacées bisannuelles de la famille des Amaryllidaceae, largement et depuis longtemps cultivée comme plante potagère pour ses bulbes de saveur et d\'odeur fortes ou pour ses feuilles. Le terme désigne aussi le bulbe de cette plante récolté comme légume. Par extension, il désigne parfois familièrement en jardinage les bulbes d\'autres plantes, généralement non comestibles (par exemple : oignon de tulipe).\nL\'oignon est utilisé à la fois comme légume et comme condiment. Le bulbe de l\'oignon se compose de bases épaissies de feuilles s\'enveloppant les unes dans les autres. De façon générale on parle d\'oignon pour tous les bulbes de liliacées, comme les tulipes. L\'échalote est une plante très voisine de l\'oignon mais elle présente un nombre de points végétatifs par bulbe plus important. La saveur de l\'échalote est également plus marquée que celle de l\'oignon.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=oignon_nu'], source: 'Wikipédia'},
    {id :41, titre : 'Petits pois', image : 'assets/legumes/petit_pois.jpg', prix : (2).toFixed(2), cat : 'Légumes', def: 'Les petits pois, pois de jardins, ou pois potagers (Pisum sativum subsp. sativum var. sativum, autonyme de Pisum sativum L.) sont les jeunes graines vertes de variétés cultivées du pois, récoltées après leur développement dans les gousses et avant leur maturité. Lorsque ces graines sont récoltées à leur maturité, elles sont appelées pois cassés. Les petits pois sont consommés comme légumes frais. Ils sont plus énergétiques (81 cal/100 g) que la majorité des légumes verts. Ils sont aussi intéressants pour leur apport en sucres solubles, en lysine et en fibres, composées en majorité d\'hémicelluloses lorsqu\'ils sont jeunes. Les petits pois crus sont aussi une bonne source de vitamine C (acide ascorbique) avec 25 mg/100 g, mais celle-ci est détruite par la cuisson. Leur consommation s\'est étendue tout au long de l\'année grâce aux techniques de conservation modernes (appertisation, surgélation). L\'expression \« petits pois \» désigne aussi, par métonymie, les gousses, ou cosses, qui enferment les graines, ainsi que les plantes qui les produisent.',
  link: ['https://www.canalvie.com/recettes/savoir-cuisiner/guide-des-aliments/petits-pois-1.1338062', 'https://informationsnutritionnelles.fr/petit-pois'], source: 'Wikipédia'},
    {id :42, titre : 'Poireaux', image : 'assets/legumes/poireaux.jpg', prix : (3.33).toFixed(2), cat : 'Légumes', def: 'Le poireau (Allium ampeloprasum var. porrum, anciennement Allium porrum) est une espèce de plante herbacée vivace largement cultivée comme plante potagère pour ses feuilles (pseudo-tiges) consommées comme légumes. Il appartient à la famille des Amaryllidacées (précédemment famille des Liliacées puis des Alliacées).\nNoms communs : poireau, porreau, poirée, poirette, asperge du pauvre.',
  link: ['https://www.passeportsante.net/fr/Nutrition/EncyclopedieAliments/Fiche.aspx?doc=poireau_nu'], source: 'Wikipédia'},
    {id :43, titre : 'Poivrons jaunes', image : 'assets/legumes/poivrons_jaunes.jpeg', prix : (1.30).toFixed(2), cat : 'Légumes', def: 'voir \"poivrons verts\"',
  link: ['santeetnutrition.com/les-bienfaits-du-poivron-jaune.htm'], source: 'Wikipédia'},
    {id :44, titre : 'Poivrons rouges', image : 'assets/legumes/poivrons_rouges.jpeg', prix : (1.30).toFixed(2), cat : 'Légumes', def: 'voir \"poivrons verts\"',
    link: ['https://www.topsante.com/nutrition-et-recettes/les-bons-aliments/fruits-et-legumes/le-poivron-rouge-ultra-vitamine-620029'], source: 'Wikipédia'},
    {id :45, titre : 'Poivrons verts', image : 'assets/legumes/poivrons_verts1.jpeg', prix : (1.30).toFixed(2), cat : 'Légumes', def: 'Le poivron est un terme souvent utilisé pour caractériser des variétés de piments doux de l\'espèce Capsicum annuum à très gros fruits (parfois appelé piment au Québec). C\'est une plante annuelle de la famille des Solanacées originaire du Mexique , d\' Amérique centrale et d\' Amérique du Sud .',
    link: ['https://www.avogel.ca/fr/nutrition/ingredients/poivrons/'], source: 'Wikipédia'},
    {id :46, titre : 'Pommes de terre', image : 'assets/legumes/pomme_de_terre.jpg', prix : (2.10).toFixed(2), cat : 'Légumes', def: 'La pomme de terre ou patate (langage familier, canadianisme et belgicisme), est un tubercule comestible produit par l’espèce Solanum tuberosum, appartenant à la famille des solanacées. Le terme désigne également la plante elle-même, plante herbacée, vivace par ses tubercules mais toujours cultivée comme une culture annuelle. La pomme de terre est une plante qui réussit dans la plupart des sols, mais elle préfère les sols légers légèrement acides. La plante est sujette aux maladies dans des sols calcaires ou manquant d’humus. La pomme de terre est originaire de la cordillère des Andes (Pérou), dans le Sud-Ouest de l\’Amérique du Sud où son utilisation remonte à environ 8 000 ans. Introduite en Europe vers la fin du xvie siècle à la suite de la découverte de l\’Amérique par les conquistadors espagnols, elle s\’est rapidement diffusée dans le monde et est en 2015 cultivée dans plus de 150 pays sous pratiquement toutes les latitudes habitées.',
  link: ['https://www.doctissimo.fr/html/nutrition/dossiers/pomme-de-terre/13883-qualites-nutritionnelles-pomme-de-terre.htm', 'https://www.avogel.ca/fr/nutrition/ingredients/pommes-de-terre/'], source: 'Wikipédia'},
    {id :47, titre : 'Salade Chicorée', image : 'assets/legumes/salade_chicoree.jpg', prix : (1.50).toFixed(2), cat : 'Légumes', def: 'Chicorée à larges feuilles Barbe de capucin. C\'est une chicorée sauvage ordinaire. Il s\'agit d\'une salade d\'hiver obtenue par la mise en forçage de racines disposées dans des couches de sable, à l\'obscurité, dans une cave par exemple. Ce forçage provoque la pousse de feuilles étiolées, longues et étroites.',
  link: ['https://monjardinmamaison.maison-travaux.fr/mon-jardin-ma-maison/plantes-par-type/plantes-aromatiques-plantes-par-type/bienfaits-de-chicoree-265572.html#item=1', 'https://www.doctissimo.fr/html/sante/phytotherapie/plante-medicinale/chicoree.htm'], source: 'Wikipédia'},
    {id :48, titre : 'Tomates cerises', image : 'assets/legumes/tomates_cerises.jpg', prix : (2).toFixed(2), cat : 'Légumes', def: 'La tomate cerise est un type de variété de tomate, cultivée comme cette dernière pour ses fruits - mais de taille réduite - consommés comme légumes. Les tomates cerises sont généralement considérées comme des hybrides entre Solanum pimpinellifolium L. et la tomate cultivée, issue de l\'espèce Solanum lycopersicum. ',
  link: ['https://www.jardiner-malin.fr/fiche/tomate-cerise.html'], source: 'Wikipédia'},
    {id :49, titre : 'Tomates', image : 'assets/legumes/tomates1.jpeg', prix : (1.99).toFixed(2), cat : 'Légumes', def: 'La Tomate (Solanum lycopersicum L.) est une espèce de plantes herbacées du genre Solanum de la famille des Solanacées, originaire du Nord-Ouest de l\'Amérique du Sud, largement cultivée pour son fruit. Le terme désigne aussi ce fruit charnu. La tomate se consomme comme un légume-fruit, crue ou cuite.',
  link: ['https://www.cuisineaz.com/articles/10-bienfaits-insoupconnes-de-la-tomate-sur-la-sante-1257.aspx', 'https://sante.lefigaro.fr/mieux-etre/nutrition-aliments/tomate/quels-bienfaits'], source: 'Wikipédia'}
  ];

  

  productPanier : Array<any> = new Array<any>();
  obsTotal : Subject<any> = new Subject<any>();
  obsQty : Subject<any> = new Subject<any>();
  obsDelete : Subject<any> = new Subject<any>();
  productsSearch : Array<any> = new Array<any>();
obsSearch : Subject<any> = new Subject<any>();
  constructor() { }
}
